name: Ping Streamlit App (keep alive)

on:
  schedule:
    - cron: '*/40 * * * *'  # Ogni 30 minuti (UTC)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping https://ancepiemonte.streamlit.app/
        run: |
          echo "‚è∞ Ping in corso..."
          curl -s -o /dev/null -w "%{http_code}\n" https://ancepiemonte.streamlit.app/